### ISSUE TITLE
关于negamax函数的调用

### ISSUE THREAD

**Issue by okman334** [YunyanDeng/doudizhu_endgame#1]
效率真的是我见过的版本最高的，但里面实现的原理一时没有弄明白。我想请教一下，negamax函数最后一个参数用LORD_PLAY，应该是能搜索出农民的出牌策略对不对？

另外， negamax.cc的第18-20行，
if (lord.empty() || farmer.empty()) {
        return -1;
    }
这里是否应该区别对待turn是FARMER_PLAY还是LORD_PLAY再决定返回-1？

**Comment by YunyanDeng** [comment]
> 另外， negamax.cc的第18-20行，
> if (lord.empty() || farmer.empty()) {
> return -1;
> }
> 这里是否应该区别对待turn是FARMER_PLAY还是LORD_PLAY再决定返回-1？
不需要，negamax中的评估值是对当前决策方而言的，双方交替出牌，所以不需要判断。
