### ISSUE TITLE
一个搜索错误的情况

### ISSUE THREAD

**Issue by Ylarod** [YunyanDeng/doudizhu_endgame#2]
测试案例:
----------------------------------------------------------------------------------------------------
欢乐斗地主残局普通第33关
先手: K Q J 10 9 8 8 6 5
后手: 小王 2 2 A K Q J 10 10 8 7 5 4

运行程序:
```
$ python3 doudizhu_endgame.py
doudizhu_endgame.py:106: SyntaxWarning: "is" with a literal. Did you mean "=="?

# todo:
  if card_dict[card] is 4 and (card << 2) > last_power:
doudizhu_endgame.py:231: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if s is not 0:
----------------------------------------
lord hand:
kqj098865
farmer hand:
y22akqj008754
----------------------------------------
lord:   ['5', '6', '8', '8', '9', '10', 'J', 'Q', 'K']
farmer: ['4', '5', '7', '8', '10', '10', 'J', 'Q', 'K', 'A', '2', '2', 'Black Joker']
search finished, use: 0.065867s
----------------------------------------
can not win
```

解决步骤:
----------------------------------------------------------------------------------------------------
先手: K Q J 10 9 8 
后手: PASS

先手:5
后手:10

先手:PASS
后手: A K Q J 10

先手:  PASS
后手: 2 2

先手: PASS
后手: 4

先手: 6
后手: 8

先手: PASS
后手: 小王

先手: PASS
后手: 5 胜利
----------------------------------------------------------------------------------------------------

不知道为啥搜索不出这个答案

**Comment by YunyanDeng** [comment]
```python
def create_straight(card_dict, min_len, size, last_power):
    card_for_straight = [x for x in card_dict if card_dict[x] >= size and x > last_power]
    if len(card_for_straight) < min_len:
        return []
```
这里的问题,导致大于A的牌也可以算在顺子里.先手出了`K Q J 10 9 8`之后,后手可以压制,就赢不了.
