### ISSUE TITLE
又一个搜索错误的情况

### ISSUE THREAD

**Issue by jackect** [YunyanDeng/doudizhu_endgame#3]
### 案例：
先手:  2 9 8 7 6 5 5 5 5 4 4
后手: 小王 2 2 K Q J 10 9 8 6 6 3
### 运行程序：
```
python3 doudizhu_endgame.py 
----------------------------------------
lord hand:
29876555544
farmer hand:
y22kqj098663
----------------------------------------
lord:   ['4', '4', '5', '5', '5', '5', '6', '7', '8', '9', '2']
farmer: ['3', '6', '6', '8', '9', '10', 'J', 'Q', 'K', '2', '2', 'Black Joker']
search finished, use: 0.376527s
----------------------------------------
can not win
```
### 正解：
先手：5 5 5 4 4
后手：PASS

先手：9 8 7 6 5
后手：8 9 10 J Q

先手：PASS
此时先手只剩一个2，后手还有 小王 2 2 K 6 6 3，先手必赢
---
看看是为啥搜索不出这个答案呢？

**Comment by YunyanDeng** [comment]
> ### 案例：
> 先手: 2 9 8 7 6 5 5 5 5 4 4
> 后手: 小王 2 2 K Q J 10 9 8 6 6 3
> 
> ### 运行程序：
> ```
> python3 doudizhu_endgame.py 
> ----------------------------------------
> lord hand:
> 29876555544
> farmer hand:
> y22kqj098663
> ----------------------------------------
> lord:   ['4', '4', '5', '5', '5', '5', '6', '7', '8', '9', '2']
> farmer: ['3', '6', '6', '8', '9', '10', 'J', 'Q', 'K', '2', '2', 'Black Joker']
> search finished, use: 0.376527s
> ----------------------------------------
> can not win
> ```
> 
> ### 正解：
> 先手：5 5 5 4 4
> 后手：PASS
> 
> 先手：9 8 7 6 5
> 后手：8 9 10 J Q
> 
> ## 先手：PASS
> 此时先手只剩一个2，后手还有 小王 2 2 K 6 6 3，先手必赢
> 看看是为啥搜索不出这个答案呢？

很久没看这个了,今晚回去看一下
